services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${APP_FORWARD_PORT-8031}:3000"
    volumes:
      - .:/app
    depends_on:
      - database
    networks:
      - outer-heaven-net

  database:
    image: postgres:15.6-alpine3.18
    container_name: outer-heaven-db
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      - POSTGRES_USER=${DB_USER:-"root"}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-"secret"}
      - POSTGRES_DB=${DB_NAME:-"edus_db"}
    volumes:
      - /home/$USER/outer-heaven-db-data:/var/lib/postgresql/data
    networks:
      - outer-heaven-net

  pgadmin:
    image: dpage/pgadmin4:8.3
    container_name: outer-heaven-pgadmin
    depends_on:
      - database
    ports:
      - "${PGADMIN_PORT:-8888}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - outer-heaven-net

networks:
  outer-heaven-net:
    driver: bridge